package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/perxibes/termdossier/internal/chunk"
	"github.com/perxibes/termdossier/internal/llm"
	"github.com/perxibes/termdossier/internal/preprocess"
	"github.com/perxibes/termdossier/internal/prompt"
	"github.com/perxibes/termdossier/internal/session"
)

// ChunkThreshold is the minimum number of events before chunking activates.
const ChunkThreshold = 15

// Generate builds a markdown report and writes it to the session directory.
// For sessions with ChunkThreshold or more events, uses chunked generation
// (summarize chunks, then generate final report from summaries).
// Set chunkSize to 0 to disable chunking.
func Generate(provider llm.Provider, meta *session.Meta, events []preprocess.ProcessedEvent, context string, tmpl *prompt.Template, chunkSize int) (string, error) {
	if context == "" {
		context = "General terminal session"
	}

	if chunkSize > 0 && len(events) >= ChunkThreshold {
		return generateChunked(provider, meta, events, context, tmpl, chunkSize)
	}
	return generateDirect(provider, meta, events, context, tmpl)
}

func generateDirect(provider llm.Provider, meta *session.Meta, events []preprocess.ProcessedEvent, context string, tmpl *prompt.Template) (string, error) {
	cmdLines := buildCommandList(events)

	userTmpl, err := template.New("user").Parse(tmpl.User)
	if err != nil {
		return "", fmt.Errorf("parse user template: %w", err)
	}

	var buf strings.Builder
	err = userTmpl.Execute(&buf, prompt.TemplateData{
		Context:      context,
		SessionID:    meta.SessionID,
		StartedAt:    meta.StartedAt,
		CommandCount: len(events),
		CommandList:  cmdLines,
	})
	if err != nil {
		return "", fmt.Errorf("build prompt: %w", err)
	}

	response, err := provider.Generate(tmpl.System, buf.String())
	if err != nil {
		return "", fmt.Errorf("LLM generate: %w", err)
	}

	return writeReport(meta, response)
}

func generateChunked(provider llm.Provider, meta *session.Meta, events []preprocess.ProcessedEvent, context string, tmpl *prompt.Template, chunkSize int) (string, error) {
	cfg := chunk.DefaultConfig()
	cfg.MaxCommandsPerChunk = chunkSize

	chunks := chunk.Split(events, cfg)
	fmt.Fprintf(os.Stderr, "Session has %d commands — splitting into %d chunks\n",
		len(events), len(chunks))

	if err := chunk.SummarizeAll(provider, chunks); err != nil {
		return "", fmt.Errorf("chunk summarization: %w", err)
	}

	finalPrompt := chunk.BuildFinalPrompt(chunks, context, meta.SessionID, meta.StartedAt, len(events))

	fmt.Fprintf(os.Stderr, "Generating final report from chunk summaries...\n")
	response, err := provider.Generate(tmpl.System, finalPrompt)
	if err != nil {
		return "", fmt.Errorf("LLM generate final: %w", err)
	}

	return writeReport(meta, response)
}

func writeReport(meta *session.Meta, response string) (string, error) {
	header := fmt.Sprintf("<!-- Generated by termdossier %s | Session %s | %s -->\n\n",
		meta.Version, meta.SessionID, time.Now().UTC().Format(time.RFC3339))

	outPath := filepath.Join(session.Dir(meta.SessionID), "report.md")
	if err := os.WriteFile(outPath, []byte(header+response), 0600); err != nil {
		return "", fmt.Errorf("write report: %w", err)
	}

	return outPath, nil
}

func buildCommandList(events []preprocess.ProcessedEvent) string {
	var sb strings.Builder
	for i, e := range events {
		marker := " "
		if e.ExitCode != 0 {
			marker = "!"
		}
		repeatInfo := ""
		if e.RepeatCount > 1 {
			repeatInfo = fmt.Sprintf(" (repeated %dx)", e.RepeatCount)
		}
		sb.WriteString(fmt.Sprintf("#%d %s[%d | %dms | %s] %s%s\n",
			i+1, marker, e.ExitCode, e.DurationMS, e.CWD, e.Stdin, repeatInfo))

		if e.ProcessedStdout != "" {
			sb.WriteString("--- output ---\n")
			sb.WriteString(e.ProcessedStdout)
			if !strings.HasSuffix(e.ProcessedStdout, "\n") {
				sb.WriteString("\n")
			}
			sb.WriteString("--- end output ---\n")
		}
	}
	return sb.String()
}
