package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/perxibes/termdossier/internal/llm"
	"github.com/perxibes/termdossier/internal/session"
	"github.com/perxibes/termdossier/internal/store"
)

const promptTemplate = `You are a technical writer generating a professional report from a recorded terminal session.

Context provided by the operator: {{ .Context }}

Session metadata:
- Session ID: {{ .SessionID }}
- Started at: {{ .StartedAt }}
- Total commands: {{ .CommandCount }}

Commands executed (format: [exit_code | duration_ms | cwd] command):
{{ .CommandList }}

Generate a structured technical report in Markdown with the following sections:
# Technical Report

## Context
## Executive Summary
## Timeline of Actions
## Detailed Command Analysis
## Observations
## Security Considerations
## Conclusion

Rules:
- Be concise and professional.
- Explain what each significant command does and why it matters.
- Flag any failed commands (non-zero exit codes).
- Note security-relevant operations.
- Do not fabricate output that wasn't recorded.
`

// Generate builds a markdown report and writes it to the session directory.
// Returns the output path.
func Generate(provider llm.Provider, meta *session.Meta, events []store.Event, context string) (string, error) {
	if context == "" {
		context = "General terminal session"
	}

	cmdLines := buildCommandList(events)

	tmpl, err := template.New("prompt").Parse(promptTemplate)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	err = tmpl.Execute(&buf, map[string]any{
		"Context":      context,
		"SessionID":    meta.SessionID,
		"StartedAt":    meta.StartedAt,
		"CommandCount": len(events),
		"CommandList":  cmdLines,
	})
	if err != nil {
		return "", fmt.Errorf("build prompt: %w", err)
	}

	response, err := provider.Generate(buf.String())
	if err != nil {
		return "", fmt.Errorf("LLM generate: %w", err)
	}

	// Prepend metadata header
	header := fmt.Sprintf("<!-- Generated by termdossier %s | Session %s | %s -->\n\n",
		meta.Version, meta.SessionID, time.Now().UTC().Format(time.RFC3339))

	outPath := filepath.Join(session.Dir(meta.SessionID), "report.md")
	if err := os.WriteFile(outPath, []byte(header+response), 0600); err != nil {
		return "", fmt.Errorf("write report: %w", err)
	}

	return outPath, nil
}

func buildCommandList(events []store.Event) string {
	var sb strings.Builder
	for _, e := range events {
		sb.WriteString(fmt.Sprintf("[%d | %dms | %s] %s\n", e.ExitCode, e.DurationMS, e.CWD, e.Stdin))
	}
	return sb.String()
}
